FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS build
WORKDIR /app


COPY OnlineCV/*.csproj ./
RUN dotnet restore

COPY OnlineCV/. ./

RUN dotnet publish "OnlineCV.csproj"  -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
EXPOSE 80
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "OnlineCV.dll"]