# Build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY OnlineCV/*.csproj ./OnlineCV/
RUN dotnet restore ./OnlineCV/OnlineCV.csproj

COPY OnlineCV/. ./OnlineCV/
WORKDIR /src/OnlineCV
RUN dotnet publish OnlineCV.csproj -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
EXPOSE 8080

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "OnlineCV.dll"]
